### ISSUE TITLE
gqlint file location

### ISSUE THREAD

**Issue by jeffwillette** [happylinks/gqlint#11]
the gqlint file works well only if the gqlint file and the current directory is the same, otherwise it has to be explicitly set on the command line.

I think it would be better if it searched some common locations such as the directory containing the file to be linted and `~/`. I would explicitly set the config myself, but I have an editor that is calling it and it seems I cannot enter a custom command myself.

What do you think?

**Comment by happylinks** [comment]
Hi, thanks for the issue. 
Indeed the way we check the .gqlint file right now is too basic.
I think we need to expand the code a bit here: https://github.com/happylinks/gqlint/blob/master/bin/gqlint.js#L33
I'd like to look into how eslint does it, I think they scan parent-folders as well.
I'll see if I can work on this soon, if you wanna help me figure out the best approach (e.g. where to look for the config-file) that would be very much welcome :)

P.S. What editor are you using with gqlint?

**Comment by jeffwillette** [comment]
I'm using Neovim with ALE. I'll take a look at how others do it to see how involved it is

**Comment by jeffwillette** [comment]
In eslint I found this file. There seems to be different functions for finding the config and placing them in a hierarchy. Im not sure where this is being called from exactly 

https://github.com/eslint/eslint/blob/5d451c510c15abc41b5bb14b4955a7db96aeb100/lib/config.js#L183

Their system looks quite complex but they are covering every case. I think the complexity could be cut down quite a lot by only covering the most obvious cases in a function with a `switch`. What do you think?

I think the hierarchy of what we should search should be something like

1. explicitly set by the cli
2. cwd
3. parent dir of the target file
4. home dir
