### ISSUE TITLE
List of possible linter "security keys" or log level

### ISSUE THREAD

**Issue by tkolleh** [happylinks/gqlint#16]
What are the different log levels printed by gqlint? 

TL:DR; Regex capture errors, warnings, etc... then map to language server plugin equivalent.

I intend to describe gqlint in the coc-settings.json file for the [coc-diagnostic plug](https://github.com/iamcco/coc-diagnostic). There a field asks for possible `securities` to capture linter output severity for the diagnostic plugin. 

[(view provided regex)](https://regex101.com/r/74iROT/1)

```
  "diagnostic-languageserver.linters": {
    "gqlint": {
      "command": "gqlint",
      "debounce": 100,
      "offsetLine": 0,
      "offsetColumn": 1,
      "sourceName": "gqlint",
      "formatLines": 1,
      "formatPattern": [
        "^\\s+(\\d+):(\\d+)\\s+(\\w+)\\s+(\\w+)\\s+(.+)$",
        {
          "line": 1,
          "column": 2,
          "endLine": 1,
          "endColumn": 2,
          "message": 5,
          "security": 3
        }
      ],
      "securities": {
        "error": "error",
        "warning": "warning",
        "note": "info"
      }
    }
  },

```

**Comment by happylinks** [comment]
Hey there, sorry I missed this issue.
gqlint outputs two types of errors:
```
"warn" or 1 - turn the rule on as a warning (doesn't affect exit code)
"error" or 2 - turn the rule on as an error (exit code will be 1)
```
Hope that helps!

**Comment by tkolleh** [comment]
Thanks for the response. I've moved to a graphql LSP.
